# Generated by Django 4.2.4 on 2023-09-12 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_tasksubject_tasktopic_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktopic',
            name='subject',
        ),
        migrations.AddField(
            model_name='tasktype',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.tasksubject'),
        ),
    ]
