# Generated by Django 4.2.4 on 2023-09-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_response_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsefile',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taskfile',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
